name: Sonar Analysis

on:
  push:
    branches:
      - main
      - develop

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Analyze with SonarCloud
        run: |
          mvn -U -B verify sonar:sonar \
            -Dsonar.projectKey=test-integrations_worklflow-test \
            -Dsonar.organization=test-integrations \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=108e4d330f2e886d1f646cb5345bb7059ee32f43 \
            -Dsonar.projectName=workflow-test
